version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    networks:
      - internal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password1
    volumes:
      - mongodb_data:/data/db

  neo4j:
    build: ./neo4j
    restart: always
    networks:
      - internal
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data

  o7-bot:
    build: .
    restart: always
    networks:
      - internal
    volumes:
      - ./config.json:/home/container/app/config.json:rw
    depends_on:
      - mongodb
      - neo4j
    environment:
      NODE_ENV: dev
      OWNERS: <discord user id>
      TOKEN: <discord bot token>
      PREFIX: ! # obsolete in favor of slash commands
      MONGO_CONNECTION_STRING: mongodb://mongo:password1@mongodb:27017
      MONGO_DATABASE: o7-bot
      NEO4J_URI: neo4j://neo4j:7687
      NEO4J_DATABASE: o7-bot
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: neo4j
      GCLOUD_AUTH_CLIENT_EMAIL:
      GCLOUD_AUTH_PRIVATE_KEY:
      GCLOUD_BUCKET:

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --cleanup --interval 30

networks:
  internal:

volumes:
  neo4j_data:
  mongodb_data: