version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password1
    volumes:
      - ./data/db:/data/db

  neo4j:
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password1
    volumes:
      - ./data/neo4j:/data

  o7-bot:
#    image: o7bot/o7-bot:latest
    build: .
    restart: always
    links:
      - mongodb
      - neo4j
    environment:
      MONGODB_CONNECTION: mongodb://mongo:password1@mongodb:27017
      NEO4J_CONNECTION: bolt://neo4j:password1@neo4j:7687
      DISCORD_TOKEN: ODE0NDM1NTM3ODg4MzQ2MTEy.GawLaw.YtMR9TsTAcMhqy8423nf987D2HTAR3Mgnw
      GCLOUD_CLIENT_EMAIL:
      GCLOUD_PRIVATE_KEY:
      GCLOUD_BUCKET_NAME: