
export enum PlanetaryResources {
  LusteringAlloy = 'Lustering Alloy',
  SheenCompound = 'Sheen Compound',
  GleamingAlloy = 'Gleaming Alloy',
  CondensedAlloy = 'Condensed Alloy',
  PreciousAlloy = 'Precious Alloy',
  MotleyCompound = 'Motley Compound',
  FiberComposite = 'Fiber Composite',
  LucentCompound = 'Lucent Compound',
  OpulentCompound = 'Opulent Compound',
  GlossyCompound = 'Glossy Compound',
  CrystalCompound = 'Crystal Compound',
  DarkCompound = 'Dark Compound',
  ReactiveGas = 'Reactive Gas',
  NobleGas = 'Noble Gas',
  BaseMetals = 'Base Metals',
  HeavyMetals = 'Heavy Metals',
  NobleMetals = 'Noble Metals',
  ReactiveMetals = 'Reactive Metals',
  ToxicMetals = 'Toxic Metals',
  IndustrialFibers = 'Industrial Fibers',
  SupertensilePlastics = 'Supertensile Plastics',
  Polyaramids = 'Polyaramids',
  Coolant = 'Coolant',
  Condensates = 'Condensates',
  ConstructionBlocks = 'Construction Blocks',
  Nanites = 'Nanites',
  SilicateGlass = 'Silicate Glass',
  SmartfabUnits = 'Smartfab Units',
  HeavyWater = 'Heavy Water',
  SuspendedPlasma = 'Suspended Plasma',
  LiquidOzone = 'Liquid Ozone',
  IonicSolutions = 'Ionic Solutions',
  OxygenIsotopes = 'Oxygen Isotopes',
  Plasmoids = 'Plasmoids',
}

export enum Minerals {
  Tritanium = 'tritanium',
  Pyerite = 'pyerite',
  Mexallon = 'mexallon',
  Isogen = 'isogen',
  Nocxium = 'nocxium',
  Zydrine = 'zydrine',
  Megacyte = 'megacyte',
  Morphite = 'morphite',
}

export enum Ores {
  Veldspar = 'veldspar',
  Plagioclase = 'plagioclase',
  Scordite = 'scordite',
  Omber = 'omber',
  Pyroxeres = 'pyroxeres',
  Kernite = 'kernite',
  DarkOchre = 'darkOchre',
  Gneiss = 'gneiss',
  Spodumain = 'spodumain',
  Hemorphite = 'hemorphite',
  Hedbergite = 'hedbergite',
  Jaspet = 'jaspet',
  Crokite = 'crokite',
  Bistot = 'bistot',
  Arkonor = 'arkonor',
  Mercoxet = 'mercoxet',
}

