name: Build release

on:
  release:
    types: [published]
    branches:
      - main
      - master
    tags:
      - "*"

concurrency:
  group: release-${{ github.event.release.tag_name }}
  cancel-in-progress: true

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --cache-folder ~/.yarn-cache

      - name: Build Code
        run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: release_artifact
          path: ./

  build-docker:
    needs: build-code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: [neo4j, bridge, cluster]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: release_artifact
          path: ./

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login docker
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./docker/${{ matrix.tags }}.dockerfile
          tags: |
            ghcr.io/${{ github.repository }}_${{ matrix.tags }}:latest
            ghcr.io/${{ github.repository }}_${{ matrix.tags }}:${{ github.event.release.tag_name }}
