name: Build test

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

concurrency:
  group: test-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: [neo4j, bridge, cluster]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --cache-folder ~/.yarn-cache

      - name: Build Code
        run: yarn build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login docker
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./docker/${{ matrix.tags }}.dockerfile
          tags: |
            ghcr.io/${{ github.repository }}_${{ matrix.tags }}:test
            ghcr.io/${{ github.repository }}_${{ matrix.tags }}:${{ github.sha }}
