name: Build release

on:
  release:
    types: [published]
    branches:
      - main
      - master
    tags:
      - '*'

concurrency: 
  group: release-${{ github.event.release.tag_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --cache-folder ~/.yarn-cache
      
      - name: Build Code
        run: yarn build

      - name: Build Docker Images
        run: |
          docker build -t ${{ github.repository }}_neo4j:latest -f docker/neo4j.dockerfile
          docker build -t ${{ github.repository }}_bridge:latest -f docker/bridge.dockerfile
          docker build -t ${{ github.repository }}_cluster:latest -f docker/cluster.dockerfile

      - name: Tag Docker Images
        run: |
          docker tag ${{ github.repository }}_neo4j:latest ${{ github.repository }}_neo4j:release-${{ github.event.release.tag_name }}
          docker tag ${{ github.repository }}_bridge:latest ${{ github.repository }}_bridge:release-${{ github.event.release.tag_name }}
          docker tag ${{ github.repository }}_cluster:latest ${{ github.repository }}_cluster:release-${{ github.event.release.tag_name }}

          docker tag ${{ github.repository }}_neo4j:latest ${{ github.repository }}_neo4j:release-${{ github.ref }}
          docker tag ${{ github.repository }}_bridge:latest ${{ github.repository }}_bridge:release-${{ github.ref }}
          docker tag ${{ github.repository }}_cluster:latest ${{ github.repository }}_cluster:release-${{ github.ref }}

      - name: Push Docker Images
        run: |
          docker push ${{ github.repository }}_neo4j:latest
          docker push ${{ github.repository }}_bridge:latest
          docker push ${{ github.repository }}_cluster:latest

          docker push ${{ github.repository }}_neo4j:release-${{ github.event.release.tag_name }}
          docker push ${{ github.repository }}_bridge:release-${{ github.event.release.tag_name }}
          docker push ${{ github.repository }}_cluster:release-${{ github.event.release.tag_name }}

          docker push ${{ github.repository }}_neo4j:release-${{ github.ref }}
          docker push ${{ github.repository }}_bridge:release-${{ github.ref }}
          docker push ${{ github.repository }}_cluster:release-${{ github.ref }}