name: Dependabot auto merge
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

concurrency:
  group: dependabot-auto-merge-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --cache-folder ~/.yarn-cache

      - name: Build Code
        run: yarn build

      - name: Build Docker Images
        run: |
          docker build -t ${{ github.username }}/o7_neo4j:test -f docker/neo4j.dockerfile
          docker build -t ${{ github.username }}/o7_bridge:test -f docker/bridge.dockerfile
          docker build -t ${{ github.username }}/o7_cluster:test -f docker/cluster.dockerfile

  auto-merge:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && success() }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
