name: Deploy to production

on:
  release:
    types: [published]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for changes
        id: check
        uses: