name: Deploy to staging

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --cache-folder ~/.yarn-cache
      
      - name: Build Code
        run: yarn build

      - name: Build Docker Images
        run: |
          docker build -t ${{ github.username }}/o7_neo4j:latest -f docker/neo4j.dockerfile
          docker build -t ${{ github.username }}/o7_bridge:latest -f docker/bridge.dockerfile
          docker build -t ${{ github.username }}/o7_cluster:latest -f docker/cluster.dockerfile

      - name: Push Docker Images
        run: |
          docker push ${{ github.username }}/o7_neo4j:latest
          docker push ${{ github.username }}/o7_bridge:latest
          docker push ${{ github.username }}/o7_cluster:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_KEY }}
          script: |
            docker pull ${{ github.username }}/o7_neo4j:latest
            docker pull ${{ github.username }}/o7_bridge:latest
            docker pull ${{ github.username }}/o7_cluster:latest
            docker-compose -f docker-compose.yml -f docker-compose.staging.yml up -d